### ISSUE TITLE
[Feature] Only save posts newer than a given date?

### ISSUE THREAD

**Issue by chipweinberger** [makuto/Liked-Saved-Image-Downloader#12]

**Comment by makuto** [comment]
Hey, sorry for no response.

I can implement this feature if it is still desired.

**Comment by chipweinberger** [comment]
Hey man! Appreciate the response!

It looks like it already tries to figure where it left off? If so, don’t
think it’s needs anymore :)

Awesome project tho!

**Comment by makuto** [comment]
Yep, sounds like `Reddit_Try_Request_Only_New` being enabled should accomplish this.

Thanks!
