### ISSUE TITLE
Broken Pipe Error

### ISSUE THREAD

**Issue by SilentSierra** [makuto/Liked-Saved-Image-Downloader#22]
Hiya, the last few times I've tried to use this I've encountered the same error.
The script will gather the liked/saved links, and once it starts the download process it'll repeat the same Broken Pipe Error that seems to originate from tornado.

If you know what the solution is I'd appreciate the help, and hopefully I'm not just being daft haha

**Comment by makuto** [comment]
Hi!
Can you make sure you have the lastest version and try again?

**Comment by makuto** [comment]
*the latest version of this repo

**Comment by SilentSierra** [comment]
I've updated to the latest version, but now after running the script it states:

ValueError: certfile "certificates/server_jupyter_based.crt.pem" does not exist

I've also ran the pip install for the modules at the same time, both with pip and pip3, so they should be up to date as well

**Comment by makuto** [comment]
You need to generate the SSL keys (see the readme):
`mkdir certificates`
`openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout certificates/server_jupyter_based.crt.key -out certificates/server_jupyter_based.crt.pem`
(Run that in the repo folder)

**Comment by SilentSierra** [comment]
When trying that it gave an error saying openssl isn't recognised. I downloaded that from google code but I'm not sure how to use it since it doesn't seem to have an install.exe or anything

**Comment by makuto** [comment]
Ah, okay, Windows is a bit trickier to get openssl.
[This page](https://kb.firedaemon.com/support/solutions/articles/4000121705) has a binary built (click the url under Mirrors).

**Comment by makuto** [comment]
You could also use [git-bash](https://gitforwindows.org/) to use openssl.

**Comment by SilentSierra** [comment]
I got it installed and it made a couple of files, but running the script gives some kind of http request error, so I've set usessl to false for now. 
Doing that gets the web server to open properly, and works until it says "Retrieving your submissions", prints out the first 0% showing progress after which it'll stop and do nothing. 

(sorry about all the problems hahaha)

**Comment by makuto** [comment]
Does the console (cmd etc) running the server print anything more?
What does `python3 redditUserImageScraper.py` print?

It's all good, I want the script to work for everyone :)

**Comment by SilentSierra** [comment]
The console doesn't say anything more, but just running that particular script gives out an error from

redditUserImageScraper.py", line 131, in <module> runLikedSavedDownloader(None)

that ends with

FileNotFoundError: [Errno 2] No such file or directory: 'output/Reddit_SavedComment_Submissions_20190528-224808.json'

**Comment by makuto** [comment]
Does an `output/` directory exist? If not, you can should add one:
`mkdir output`
Try it again after that.

**Comment by SilentSierra** [comment]
That got it to work! It didn't print out a 'process complete' message, but it downloaded, as far as I can see, everything I've liked/saved (apart from a few gyfcats but you said you're working on that in another thread) so I'll take that as a success haha

**Comment by makuto** [comment]
Awesome. Give the Liked Saved Downloader Server a try and see if it works now.

**Comment by SilentSierra** [comment]
Yeah it works now!

**Comment by makuto** [comment]
Great! I'm going to leave this issue open until I fix the following things:
- Automatically create `output/` directory if it doesn't exist
- Update ReadMe with `Generate_Certificates.sh` and note on `UseSSL`
