### ISSUE TITLE
Add support for Reddit Videos

### ISSUE THREAD

**Issue by makuto** [makuto/Liked-Saved-Image-Downloader#24]
`v.redd.it` links don't work.

**Comment by OddMagnet** [comment]
hey, not sure if this is gonna be helpful for this issue, but "youtube-dl" can download v.redd.it links.
License shouldn't be a problem.

github: https://github.com/ytdl-org/youtube-dl

**Comment by makuto** [comment]
It is helpful, thanks for the tip!
If I integrate youtube-dl for v.redd.it, I might as well make an option and add support for liked youtube links :)

**Comment by OddMagnet** [comment]
do you think that would work for other nsfw video sites too?

**Comment by makuto** [comment]
Yes, it looks like youtube-dl [supports a whole host of sites](http://ytdl-org.github.io/youtube-dl/supportedsites.html). I created an issue, #34 for integrating youtube-dl for other sites. 
I had no idea youtube-dl was so versatile. Definitely useful 👍
