### ISSUE TITLE
Gfycat downloads not working

### ISSUE THREAD

**Issue by OddMagnet** [makuto/Liked-Saved-Image-Downloader#62]
Hello,

I just pulled the latest changes and noticed, that Gfycat downloads don't seem to work.
I get the following message

> Gfycat {MY_SECRET} means https://gfycat.com/somevideo url not downloading

I checked that the settings file that is being used has the correct secret and key and verified it via gfycat too.

Not very well versed in python, but this line of output seems to come from "videoDownloader.py", line 62 and following

```
if settings.settings['Gfycat_Client_id'] and 'gfycat.com' in url:
                print("Gfycat {} means {} url not downloading".format(settings.settings['Gfycat_Client_id'], url))
                isBlacklisted = True
```

to me it looks like if it finds a client_id in the settings and the url has gfycat.com in it, then it will print the message, and then set isBlacklisted.
That doesn't make much sense too me, since I'd expect to not get a message in that scenario and just have the video downloaded

**Comment by makuto** [comment]
Alright, thanks for the quick report! I will take a look once I get home.

**Comment by makuto** [comment]
It looks like the message was confusing, so I removed it. Gfys will be downloaded by the Gfycat API instead of the video downloader, if you have Gfycat API keys.
Let me know if you see other issues :).
