### ISSUE TITLE
runScript.html not connecting to server

### ISSUE THREAD

**Issue by flingwing** [makuto/Liked-Saved-Image-Downloader#71]
The web interface indicates:
Not connected to server 
then eventually displays (when using chrome, not observed in safari):
Connection to server lost. Reload the page to attempt to reconnect.

The download new content button doesn't respond. 

Another observation is when the redditUserScraper is running in the background and you click on the 'download new content' button it disappears.

**Comment by makuto** [comment]
It sounds like the web socket is having trouble connecting. Do you have some sort of DNS, proxy server, or something that would change the address? Or do you connect directly to the server via e.g. `https://192.168.0.2:8888`?
Do you have any script blockers running?

**Comment by makuto** [comment]
And what does the server say when you visit that page? Any mention of rejecting a connection?
Do you have HTTPS disabled?

**Comment by flingwing** [comment]
no dns, proxy or anything running interference. I can connect directly to the server via localhost:8888 (and the page launches when the server is started). I have set up authentication. Https is disabled. 

By Imgur authentication do you mean the api settings? If so, yes.

**Comment by makuto** [comment]
Ah, I must've broken websocket HTTP support when moving everything to HTTPS. I'll see if I can fix that via templatizing the websocket connections or something.

**Comment by flingwing** [comment]
I suppose I could test that for you by switching over to https correct?

**Comment by flingwing** [comment]
Set flag to True, and I was able to connect to server and run script but this was posted in the console:

`Running downloader.
Output: output
Downloader encountered a problem. Check your server output.`

and python crashed.

**Comment by makuto** [comment]
I made #73 for your new issue.
