### ISSUE TITLE
OSX Error when forking downloader process

### ISSUE THREAD

**Issue by makuto** [makuto/Liked-Saved-Image-Downloader#73]
Set flag to True, and I was able to connect to server and run script but this was posted in the console:

Running downloader. Output: output Downloader encountered a problem. Check your server output.

`Output: output
objc[29889]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[29889]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
Lost connection to subprocess!

`

and python crashed.

**Comment by makuto** [comment]
See these URLs:
- [StackOverflow on the issue](https://stackoverflow.com/questions/50168647/multiprocessing-causes-python-to-crash-and-gives-an-error-may-have-been-in-progr)
- [Workaround](https://github.com/ansible/ansible/issues/32499)

**Comment by makuto** [comment]
The readme now suggests the workaround. If anyone writes a shell script for OSX which successfully applies the workaround and runs the server, please comment on this issue with the source. I don't have a Mac so I can't test such a script.

**Comment by flingwing** [comment]
this worked, many thanks!
