### ISSUE TITLE
Can't Run LSID

### ISSUE THREAD

**Issue by JoGaTo** [makuto/Liked-Saved-Image-Downloader#86]
Tried to install and run this for the first time; tried `poetry run python3 LikedSavedDownloaderServer.py` many times, on python 3.8 and 3.9, only to get this:

```
FileNotFoundError

  [WinError 2] The system cannot find the file specified

  at c:\users\****\appdata\local\programs\python\python39-32\lib\subprocess.py:1416 in _execute_child
      1412│             sys.audit("subprocess.Popen", executable, args, cwd, env)
      1413│
      1414│             # Start the process
      1415│             try:
    → 1416│                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      1417│                                          # no special security
      1418│                                          None, None,
      1419│                                          int(not close_fds),
      1420│                                          creationflags,
```
I dunno wtf is going on here...

**Comment by makuto** [comment]
Are you running the release or from source?

Does this happen during startup or when hitting the Download/run script button?

Did you run 'poetry install -e security'?

**Comment by JoGaTo** [comment]
Both

Dunno about the second question since I've yet to even localhost because I'm so busy figuring out this

I ran through `pip3 install poetry` as it's the only thing that even worked `poetry install -e security` did absolutely nothing.

**Comment by makuto** [comment]
Do you have a strong preference for running from source? I can make you a release that will be much simpler to run, with the latest version.

Going off your error, it looks like something strange with your Python installation, but I can't be sure.

**Comment by JoGaTo** [comment]
Tried the ContentCollector thing but was unable to extract anything plus localhost kept not responding sometimes. Yeah, maybe I will need a simpler version of this.29.12.2020, 14:14, "Macoy Madson" <notifications@github.com>:
Do you have a strong preference for running from source? I can make you a release that will be much simpler to run, with the latest version.
Going off your error, it looks like something strange with your Python installation, but I can't be sure.

**Comment by makuto** [comment]
Your console output with the ContentCollector release may be help to debug the hanging issue. What do you mean by not being able to extract anything?

Is there a specific site you are trying to download from, or do you also want the browsing features?

**Comment by makuto** [comment]
Closed because it is stale.
